//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordForUs.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordForUs.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Enter additional data
        ///            format --&lt;key&gt; &lt;value&gt;
        ///            write &apos;end&apos; or empty string for finish:
        ///        .
        /// </summary>
        internal static string Add_AdditionalDataPrompt {
            get {
                return ResourceManager.GetString("Add_AdditionalDataPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password was added in storage..
        /// </summary>
        internal static string Add_AddPassword {
            get {
                return ResourceManager.GetString("Add_AddPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Login:.
        /// </summary>
        internal static string Add_EnterLoginPrompt {
            get {
                return ResourceManager.GetString("Add_EnterLoginPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter PASSWORD or enter Y/y to generate password automate:.
        /// </summary>
        internal static string Add_EnterPasswordPrompt {
            get {
                return ResourceManager.GetString("Add_EnterPasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter URL address:.
        /// </summary>
        internal static string Add_EnterURLPrompt {
            get {
                return ResourceManager.GetString("Add_EnterURLPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization completed..
        /// </summary>
        internal static string Base_SynchronizationCompleted {
            get {
                return ResourceManager.GetString("Base_SynchronizationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password was changed..
        /// </summary>
        internal static string ChangePass_PasswordChanged {
            get {
                return ResourceManager.GetString("ChangePass_PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are more than one entry with the specified ID. Please, specify the search criteria..
        /// </summary>
        internal static string ChangePass_ThereAreMoreThanOne {
            get {
                return ResourceManager.GetString("ChangePass_ThereAreMoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no entry with the specified ID..
        /// </summary>
        internal static string ChangePass_ThereIsNoEntry {
            get {
                return ResourceManager.GetString("ChangePass_ThereIsNoEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password was deleted..
        /// </summary>
        internal static string Delete_PasswordDeleted {
            get {
                return ResourceManager.GetString("Delete_PasswordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program is trying to execute an empty command - something is wrong!.
        /// </summary>
        internal static string Empty_TryingToExecute {
            get {
                return ResourceManager.GetString("Empty_TryingToExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        internal static string FindCommand_Done {
            get {
                return ResourceManager.GetString("FindCommand_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program didn&apos;t find anything..
        /// </summary>
        internal static string FindCommand_NotFound {
            get {
                return ResourceManager.GetString("FindCommand_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to find ID:{0} URL:{1} Name:{3}....
        /// </summary>
        internal static string FindCommand_TryingToFind {
            get {
                return ResourceManager.GetString("FindCommand_TryingToFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated Password: {0}.
        /// </summary>
        internal static string GeneratePass_GeneratePass {
            get {
                return ResourceManager.GetString("GeneratePass_GeneratePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command name. See all command list..
        /// </summary>
        internal static string Help_InvalidСommandName {
            get {
                return ResourceManager.GetString("Help_InvalidСommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End import command..
        /// </summary>
        internal static string Import_End {
            get {
                return ResourceManager.GetString("Import_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has been parsed..
        /// </summary>
        internal static string Import_FileParsed {
            get {
                return ResourceManager.GetString("Import_FileParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password file has been opened..
        /// </summary>
        internal static string Open_FileOpened {
            get {
                return ResourceManager.GetString("Open_FileOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to open(o) or to import(i) the file with stored passwords..
        /// </summary>
        internal static string OpenFilePrompt {
            get {
                return ResourceManager.GetString("OpenFilePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write hash iteration for password please:.
        /// </summary>
        internal static string SetPass_HashIterationPromt {
            get {
                return ResourceManager.GetString("SetPass_HashIterationPromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please enter a positive integer..
        /// </summary>
        internal static string SetPass_InvalidInputInteger {
            get {
                return ResourceManager.GetString("SetPass_InvalidInputInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is empty..
        /// </summary>
        internal static string SetPass_IsEmpty {
            get {
                return ResourceManager.GetString("SetPass_IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write password please:.
        /// </summary>
        internal static string SetPass_WritePromt {
            get {
                return ResourceManager.GetString("SetPass_WritePromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings updated successfully..
        /// </summary>
        internal static string SetSettings_Success {
            get {
                return ResourceManager.GetString("SetSettings_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Settings:.
        /// </summary>
        internal static string ShowSettings_CurrentSettings {
            get {
                return ResourceManager.GetString("ShowSettings_CurrentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --PasswordForUs started.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
